services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_service
    ports:
      - "8000:8000"
    networks:
      - iomsnetwork
    
  frontend:
    build:
      context: ./frontend_typescript
      dockerfile: Dockerfile
    container_name: frontend_service
    ports:
      - "5173:80"
    networks:
      - iomsnetwork

networks:
  iomsnetwork:
    driver: bridge
